-- +goose Up
CREATE TABLE link_visits (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_id     bigint NOT NULL REFERENCES links (id) ON DELETE CASCADE,
    ip          varchar(45) NOT NULL,
    user_agent  varchar(512) NOT NULL DEFAULT '',
    referer     varchar(2048) NOT NULL DEFAULT '',
    status      int NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX link_visits_link_id_idx ON link_visits (link_id);
CREATE INDEX link_visits_created_at_idx ON link_visits (created_at);

-- +goose Down
DROP TABLE IF EXISTS link_visits;
