-- +goose Up
CREATE TABLE links (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_url varchar(2048) NOT NULL,
    short_name   varchar(64) NOT NULL,
    short_url    varchar(512) NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT links_short_name_unique UNIQUE (short_name)
);

-- +goose Down
DROP TABLE IF EXISTS links;
