// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createLinkStmt, err = db.PrepareContext(ctx, createLink); err != nil {
		return nil, fmt.Errorf("error preparing query CreateLink: %w", err)
	}
	if q.deleteLinkStmt, err = db.PrepareContext(ctx, deleteLink); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteLink: %w", err)
	}
	if q.getLinkByIDStmt, err = db.PrepareContext(ctx, getLinkByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetLinkByID: %w", err)
	}
	if q.getLinksStmt, err = db.PrepareContext(ctx, getLinks); err != nil {
		return nil, fmt.Errorf("error preparing query GetLinks: %w", err)
	}
	if q.updateLinkStmt, err = db.PrepareContext(ctx, updateLink); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateLink: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createLinkStmt != nil {
		if cerr := q.createLinkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createLinkStmt: %w", cerr)
		}
	}
	if q.deleteLinkStmt != nil {
		if cerr := q.deleteLinkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteLinkStmt: %w", cerr)
		}
	}
	if q.getLinkByIDStmt != nil {
		if cerr := q.getLinkByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLinkByIDStmt: %w", cerr)
		}
	}
	if q.getLinksStmt != nil {
		if cerr := q.getLinksStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLinksStmt: %w", cerr)
		}
	}
	if q.updateLinkStmt != nil {
		if cerr := q.updateLinkStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateLinkStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db              DBTX
	tx              *sql.Tx
	createLinkStmt  *sql.Stmt
	deleteLinkStmt  *sql.Stmt
	getLinkByIDStmt *sql.Stmt
	getLinksStmt    *sql.Stmt
	updateLinkStmt  *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:              tx,
		tx:              tx,
		createLinkStmt:  q.createLinkStmt,
		deleteLinkStmt:  q.deleteLinkStmt,
		getLinkByIDStmt: q.getLinkByIDStmt,
		getLinksStmt:    q.getLinksStmt,
		updateLinkStmt:  q.updateLinkStmt,
	}
}
