// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Link struct {
	ID          int64
	OriginalUrl string
	ShortName   string
	ShortUrl    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
